### ISSUE TITLE
Undo button navigates back to Login Activity

### ISSUE THREAD

**Issue by Marcell-Juhasz** [Marcell-Juhasz/secret-diary#21]
@RedJocker I agree that a real app should work this way, but maybe this is not the most important issue to work on, since the app works well without this feature.
Is there a way in robolectric to check the backstack of the Activities?

**Comment by RedJocker** [comment]
I have to do some research. 
I know that there are at least two ways to implement this feature. 
One is by calling finish() after startActivity(intent). Another is by setting the flags of the intent with ``it.flags = it.flags or (Intent.FLAG_ACTIVITY_CLEAR_TASK or Intent.FLAG_ACTIVITY_NEW_TASK)`` 

Do you know any other possible implementation for this feature? 

I don't think there are direct ways to check the backstack because I don't think there is one. When we setup the test we setup to test an Activity, we are not testing the whole application. I don't think there is a way to test the whole thing with Robolectric.

I think to do this we have to check if either the flags are set like above, which is probably easy to do since we are already checking things on the intent in tests, or if finish() was called. I think we can test if finish() was called by checking activity.isFinishing.

Can you try to make something with this info?

If you can't do it I will try doing myself, but I'm a little busy with some other stuff.

**Comment by Marcell-Juhasz** [comment]
I guess it works.
I've written a function `testLoginActivityFinished()` in stage 5 test.
You can check it on both the 'solution' and the 'stepik' branch.
The test checks if the user set the two intent flags or called the finish() function

**Comment by RedJocker** [comment]
good, I can't test right now,  but will do soon.

**Comment by RedJocker** [comment]
it seems to be working, you can close this if you think this is finished
